baseURL = "https://lake-afton-public-observatory.github.io/volunteer_handbook/"
languageCode = "en-us"
title = "Lake Afton Public Observatory - Volunteer Handbook"
theme = "hugo-theme-techdoc"
uglyURLs = false

[outputs]
home = [ "HTML", "JSON"]

[markup.goldmark.renderer]
unsafe = true

############################# Params ##############################

[params]
    menu_style = "slide-menu" 
    ordersectionsby = "weight"

    custom_font_color = "#ffffff"
    custom_background_color = "#000000"